'use client';

import Link from 'next/link';
import { ArrowLeft, Minus, Plus, Trash2 } from 'lucide-react';
import { useCart } from '@/components/cart/CartProvider';

export default function CartView() {
  const cart = useCart(); const items = cart?.items || []; const subtotal = cart?.subtotal || 0; const shipping = subtotal >= 3000 ? 0 : subtotal ? 80 : 0; const total = subtotal + shipping;
  if (!items.length) return <main className="container cart-page"><div className="cart-heading"><p>Shopping bag</p><h1>Your cart</h1></div><div className="cart-empty"><h2>Your cart is empty</h2><p>Discover practical, quality products for your everyday.</p><Link className="btn" href="/shop">Continue shopping</Link></div></main>;
  return <main className="container cart-page"><div className="cart-heading"><p>Shopping bag</p><h1>Cart</h1></div><div className="cart-layout"><section className="cart-items"><div className="cart-table-head"><span>Product</span><span>Price</span><span>Quantity</span><span>Total</span></div>{items.map(item => { const price = Number(item.product?.salePrice || item.product?.regularPrice || 0); const regular = Number(item.product?.regularPrice || 0); return <article className="cart-row" key={item.id}><div className="cart-product"><div className="cart-product-image">{item.product?.images?.[0]?.url ? <img src={item.product.images[0].url} alt={item.product.name}/> : '📦'}</div><div><Link href={`/product/${item.product?.slug}`}><strong>{item.product?.name || 'Product'}</strong></Link>{regular > price && <small>Save ৳{(regular - price).toLocaleString()}</small>}</div></div><div className="cart-price">৳{price.toLocaleString()}{regular > price && <del>৳{regular.toLocaleString()}</del>}</div><div className="cart-quantity"><button aria-label="Decrease quantity" disabled={item.quantity <= 1} onClick={() => cart.update(item.productId, item.quantity - 1)}><Minus size={15}/></button><span>{item.quantity}</span><button aria-label="Increase quantity" onClick={() => cart.update(item.productId, item.quantity + 1)}><Plus size={15}/></button></div><div className="cart-total">৳{(price * item.quantity).toLocaleString()}<button className="cart-remove" aria-label="Remove item" onClick={() => cart.remove(item.productId)}><Trash2 size={17}/></button></div></article>; })}<Link href="/shop" className="continue-shopping"><ArrowLeft size={16}/> Continue shopping</Link></section><CartSummary subtotal={subtotal} shipping={shipping} total={total}/></div></main>;
}

function CartSummary({ subtotal, shipping, total }) { return <aside className="cart-summary"><h2>Cart totals</h2><details><summary>Have a coupon?</summary><div className="coupon-row"><input placeholder="Coupon code"/><button type="button">Apply</button></div></details><div className="summary-line"><span>Subtotal</span><strong>৳{subtotal.toLocaleString()}</strong></div><div className="summary-line"><span>Shipping</span><strong>{shipping ? `৳${shipping.toLocaleString()}` : 'Free'}</strong></div><div className="summary-total"><span>Estimated total</span><strong>৳{total.toLocaleString()}</strong></div><Link href="/checkout" className="btn cart-checkout">Proceed to checkout</Link></aside>; }
