import { prisma } from '@/lib/prisma';
import { requireAdmin, jsonError } from '@/lib/admin';
import { z } from 'zod';
const productSchema=z.object({name:z.string().min(2),slug:z.string().min(2),sku:z.string().min(2),categoryId:z.string().min(1),regularPrice:z.coerce.number().nonnegative(),salePrice:z.preprocess(value=>value===''?null:value,z.coerce.number().nonnegative().nullable()).optional(),costPrice:z.preprocess(value=>value===''?null:value,z.coerce.number().nonnegative().nullable()).optional(),stock:z.coerce.number().int().nonnegative(),lowStock:z.coerce.number().int().nonnegative().default(5),brand:z.string().nullable().optional(),shortDescription:z.string().nullable().optional(),description:z.string().nullable().optional(),active:z.boolean().default(true),featured:z.boolean().default(false),images:z.array(z.object({url:z.string().min(1),alt:z.string().optional().nullable(),isPrimary:z.boolean().optional()})).default([])});
export async function GET(request){try{await requireAdmin();const {searchParams}=new URL(request.url);const q=searchParams.get('q')||undefined;const categoryId=searchParams.get('categoryId')||undefined;const products=await prisma.product.findMany({where:{categoryId,...(q?{OR:[{name:{contains:q}},{sku:{contains:q}}]}:{})},include:{category:true,images:true},orderBy:{createdAt:'desc'}});return Response.json(products)}catch(error){return jsonError(error)}}
function imageRows(images){return images.map((image,index)=>({url:image.url,alt:image.alt||null,sortOrder:index}));}
const detailInclude={category:true,images:{orderBy:{sortOrder:'asc'}}};
export async function POST(request){try{await requireAdmin();const {images,...data}=productSchema.parse(await request.json());const product=await prisma.product.create({data:{...data,images:{create:imageRows(images)}},include:detailInclude});return Response.json(product,{status:201})}catch(error){return jsonError(error)}}
export async function PATCH(request){try{await requireAdmin();const {id,images,...input}=await request.json();const data=productSchema.partial().parse(input);const product=await prisma.$transaction(async tx=>{if(images!==undefined){await tx.productImage.deleteMany({where:{productId:id}});}return tx.product.update({where:{id},data:{...data,...(images!==undefined?{images:{create:imageRows(images)}}:{})},include:detailInclude});});return Response.json(product)}catch(error){return jsonError(error)}}
export async function DELETE(request){try{await requireAdmin();const id=new URL(request.url).searchParams.get('id');if(!id)throw new Error('Product id is required.');return Response.json(await prisma.product.update({where:{id},data:{active:false}}))}catch(error){return jsonError(error)}}
