import Link from 'next/link';
import { prisma } from '@/lib/prisma';
export default async function Admin(){
	const [sales,orders,customers,products,pending,processing,shipped,delivered,cancelled,lowStock,outOfStock,recentOrders,recentCustomers]=await Promise.all([
		prisma.order.aggregate({where:{paymentStatus:'PAID'},_sum:{total:true}}),
		prisma.order.count(),prisma.user.count({where:{role:'USER'}}),prisma.product.count(),
		prisma.order.count({where:{status:'PENDING'}}),prisma.order.count({where:{status:'PROCESSING'}}),prisma.order.count({where:{status:'SHIPPED'}}),prisma.order.count({where:{status:'DELIVERED'}}),prisma.order.count({where:{status:'CANCELLED'}}),
		prisma.product.count({where:{active:true,stock:{gt:0,lte:5}}}),prisma.product.count({where:{active:true,stock:0}}),
		prisma.order.findMany({orderBy:{createdAt:'desc'},take:6,select:{orderNumber:true,customerName:true,total:true,status:true,createdAt:true}}),
		prisma.user.findMany({where:{role:'USER'},orderBy:{createdAt:'desc'},take:5,select:{name:true,email:true,createdAt:true}})
	]);
	const money=Number(sales._sum.total||0).toLocaleString();
	return <><div className="page-title" style={{paddingTop:0}}><div className="eyebrow" style={{color:'var(--coral)'}}>Live store overview</div><h1>Good morning, admin.</h1></div><div className="stat-grid"><div className="stat"><span className="muted">Total sales</span><strong>৳{money}</strong><small className="muted">Paid orders only</small></div><div className="stat"><span className="muted">Orders</span><strong>{orders}</strong><small className="muted">{pending} pending</small></div><div className="stat"><span className="muted">Customers</span><strong>{customers}</strong><small className="muted">Registered users</small></div><div className="stat"><span className="muted">Products</span><strong>{products}</strong><small className="muted">{lowStock} low stock · {outOfStock} out</small></div></div><div className="stat-grid" style={{marginTop:16}}>{[['Pending',pending],['Processing',processing],['Shipped',shipped],['Delivered',delivered],['Cancelled',cancelled]].map(([label,value])=><div className="stat" key={label}><span className="muted">{label}</span><strong>{value}</strong></div>)}</div><div className="section" style={{paddingBottom:0}}><div className="section-head"><h2>Recent orders</h2><Link href="/admin/orders">View all</Link></div>{recentOrders.length?<table className="table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{recentOrders.map(order=><tr key={order.orderNumber}><td>{order.orderNumber}</td><td>{order.customerName}</td><td>{order.createdAt.toLocaleDateString()}</td><td>৳{Number(order.total).toLocaleString()}</td><td>{order.status}</td></tr>)}</tbody></table>:<p className="muted">No orders yet.</p>}</div><div className="section" style={{paddingBottom:0}}><div className="section-head"><h2>Recent customers</h2><Link href="/admin/customers">View all</Link></div>{recentCustomers.length?<table className="table"><thead><tr><th>Name</th><th>Email</th><th>Joined</th></tr></thead><tbody>{recentCustomers.map(customer=><tr key={customer.email}><td>{customer.name}</td><td>{customer.email}</td><td>{customer.createdAt.toLocaleDateString()}</td></tr>)}</tbody></table>:<p className="muted">No customers yet.</p>}</div></>}
