'use client';

import Link from 'next/link';
import { ArrowRight, Baby, Check, ChevronDown, ChevronRight, Heart, Home, Leaf, MoonStar, PackageCheck, RotateCcw, Search, ShieldCheck, ShoppingBag, ShoppingBasket, ShoppingCart, SlidersHorizontal, Truck, UsersRound, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useCart } from '@/components/cart/CartProvider';
import styles from './ComboProductsPage.module.css';

const priceRanges = [{ label: '৳500 - ৳1,000', min: 500, max: 1000 }, { label: '৳1,000 - ৳2,000', min: 1000, max: 2000 }, { label: '৳2,000 - ৳3,000', min: 2000, max: 3000 }, { label: '৳3,000+', min: 3000, max: Infinity }];
function makeCombo(product) {
  const price = Number(product.salePrice || product.regularPrice || 0);
  const oldPrice = Number(product.regularPrice || 0);
  const itemCount = product.comboItems?.reduce((total, item) => total + Number(item.quantity || 1), 0) || 0;
  const discount = oldPrice > price ? Math.round(((oldPrice - price) / oldPrice) * 100) : 0;
  return { ...product, comboCategory: product.category?.name || 'Combo', itemCount, price, oldPrice, discount, savings: Math.max(0, oldPrice - price), image: product.images?.[0]?.url || '' };
}

export default function ComboProductsPage({ products }) {
  const cart = useCart();
  const combos = useMemo(() => products.map(makeCombo), [products]);
  const [category, setCategory] = useState('All');
  const [selectedRanges, setSelectedRanges] = useState([]);
  const [sort, setSort] = useState('popular');
  const [filterOpen, setFilterOpen] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [ratingFilter, setRatingFilter] = useState(0);
  const [availability, setAvailability] = useState('All');
  const categories = useMemo(() => Array.from(new Set(combos.map((combo) => combo.comboCategory).filter(Boolean))).sort().map((name) => ({ name: `${name} Combo`, value: name, count: combos.filter((combo) => combo.comboCategory === name).length })), [combos]);
  const brands = useMemo(() => Array.from(new Set(combos.map((combo) => combo.brandRelation?.name || combo.brand).filter(Boolean))).sort(), [combos]);
  const [brand, setBrand] = useState('All');
  const visibleCombos = useMemo(() => {
    const filtered = combos.filter((combo) => (category === 'All' || combo.comboCategory === category) && (brand === 'All' || (combo.brandRelation?.name || combo.brand) === brand) && (!selectedRanges.length || selectedRanges.some((range) => combo.price >= range.min && combo.price <= range.max)) && (!ratingFilter || Number(combo.rating || 0) >= ratingFilter) && (availability === 'All' || (availability === 'In stock' ? Number(combo.stock || 0) > 0 : Number(combo.stock || 0) < 1)));
    return [...filtered].sort((a, b) => sort === 'newest' ? String(b.id).localeCompare(String(a.id)) : sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : sort === 'discount' ? b.discount - a.discount : b.itemCount - a.itemCount);
  }, [availability, brand, category, combos, ratingFilter, selectedRanges, sort]);
  useEffect(() => setCurrentPage(1), [availability, brand, category, ratingFilter, selectedRanges, sort]);
  const totalPages = Math.max(1, Math.ceil(visibleCombos.length / 12));
  const pageCombos = visibleCombos.slice((currentPage - 1) * 12, currentPage * 12);
  function toggleRange(range) { setSelectedRanges((current) => current.some((item) => item.min === range.min) ? current.filter((item) => item.min !== range.min) : [...current, range]); }
  function resetFilters() { setCategory('All'); setBrand('All'); setSelectedRanges([]); setRatingFilter(0); setAvailability('All'); }
  const filterProps = { category, setCategory, categories, brand, setBrand, brands, selectedRanges, toggleRange, ratingFilter, setRatingFilter, availability, setAvailability, resetFilters };
  return <main className={styles.page}><div className={styles.pageShell}><Breadcrumb /><ComboPageHeader /><div className={styles.contentLayout}><FilterSidebar {...filterProps} /><section className={styles.results}><div className={styles.mobileToolbar}><button type="button" onClick={() => setFilterOpen(true)}><SlidersHorizontal size={16} /> Filter Combo</button><span>{visibleCombos.length} combos</span></div><ProductToolbar count={visibleCombos.length} sort={sort} setSort={setSort} />{pageCombos.length ? <div className={styles.productGrid}>{pageCombos.map((combo) => <ComboProductCard key={combo.id} combo={combo} cart={cart} />)}</div> : <EmptyState resetFilters={resetFilters} />}{totalPages > 1 && <div className={styles.pagination}><button type="button" disabled={currentPage === 1} onClick={() => setCurrentPage((page) => page - 1)}>Previous</button><span>Page {currentPage} of {totalPages}</span><button type="button" disabled={currentPage === totalPages} onClick={() => setCurrentPage((page) => page + 1)}>Next</button></div>}</section></div><PromoBanners /><ComboCategorySection setCategory={setCategory} /><TrustSection /></div><MobileFilterDrawer open={filterOpen} close={() => setFilterOpen(false)} {...filterProps} /></main>;
}

function Breadcrumb() { return <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight size={13} /><span>Combo Products</span></nav>; }
function ComboPageHeader() { return <header className={styles.heroHeader}><div><span className={styles.eyebrow}>CURATED SAVINGS</span><h1>Combo Products</h1><p>সাশ্রয়ী মূল্যে আপনার নিত্যপ্রয়োজনীয় পণ্য নিয়ে আমাদের বিশেষ কম্বো প্যাকেজ সমূহ</p></div><div className={styles.featureCards}><FeatureCard icon={<Leaf size={19} />} title="Save More" text="কম দামে বেশি পণ্য" /><FeatureCard icon={<ShieldCheck size={19} />} title="Best Quality" text="100% কোয়ালিটি পণ্য" /><FeatureCard icon={<Truck size={19} />} title="Fast Delivery" text="দ্রুত ও নিরাপদ ডেলিভারি" /></div></header>; }
function FeatureCard({ icon, title, text }) { return <div className={styles.featureCard}><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>; }
function FilterSidebar(props) { return <aside className={styles.filterSidebar}><div className={styles.filterTitle}><strong>Filter Combo</strong><button type="button" onClick={props.resetFilters}>Reset</button></div><FilterOptions {...props} /><button className={styles.applyButton} type="button">Apply Filter <ArrowRight size={15} /></button></aside>; }
function FilterOptions({ category, setCategory, categories, brand, setBrand, brands, selectedRanges, toggleRange, ratingFilter, setRatingFilter, availability, setAvailability }) { return <div className={styles.filterOptions}><div className={styles.filterGroup}><h3>Categories <ChevronDown size={14} /></h3><button type="button" className={category === 'All' ? styles.activeFilter : ''} onClick={() => setCategory('All')}><span>All Combos</span><small>{categories.reduce((total, item) => total + item.count, 0)}</small></button>{categories.map((item) => <button type="button" className={category === item.value ? styles.activeFilter : ''} key={item.value} onClick={() => setCategory(item.value)}><span>{item.name}</span><small>{item.count}</small></button>)}</div>{brands.length > 0 && <div className={styles.filterGroup}><h3>Brands <ChevronDown size={14} /></h3><select className={styles.filterSelect} value={brand} onChange={(event) => setBrand(event.target.value)}><option value="All">All Brands</option>{brands.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>}<div className={styles.filterGroup}><h3>Price Range <ChevronDown size={14} /></h3>{priceRanges.map((range) => <label key={range.label}><input type="checkbox" checked={selectedRanges.some((item) => item.min === range.min)} onChange={() => toggleRange(range)} /><span>{range.label}</span></label>)}</div><div className={styles.filterGroup}><h3>Rating <ChevronDown size={14} /></h3>{[4, 3, 2].map((rating) => <button type="button" className={ratingFilter === rating ? styles.activeFilter : ''} key={rating} onClick={() => setRatingFilter(rating)}><span>★ {rating}+ rating</span></button>)}</div><div className={styles.filterGroup}><h3>Availability <ChevronDown size={14} /></h3>{['All', 'In stock', 'Out of stock'].map((value) => <button type="button" className={availability === value ? styles.activeFilter : ''} key={value} onClick={() => setAvailability(value)}><span>{value}</span></button>)}</div></div>; }
function ProductToolbar({ count, sort, setSort }) { return <div className={styles.productToolbar}><span>Showing {count} combo products</span><label>Sort by <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="popular">Popularity</option><option value="newest">Newest</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="discount">Discount</option></select></label></div>; }
function ComboProductCard({ combo, cart }) { const [saved, setSaved] = useState(false); const [wishlistLoading, setWishlistLoading] = useState(true); const [added, setAdded] = useState(false); const [adding, setAdding] = useState(false); useEffect(() => { let cancelled = false; fetch('/api/wishlist', { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then((data) => { if (!cancelled) setSaved(Boolean(data?.items?.some((item) => String(item.productId) === String(combo.id)))); }).catch(() => {}).finally(() => { if (!cancelled) setWishlistLoading(false); }); return () => { cancelled = true; }; }, [combo.id]); async function addToCart() { if (adding || Number(combo.stock || 0) <= 0) return; setAdding(true); const result = await cart.add(combo); if (result?.ok) { setAdded(true); window.setTimeout(() => setAdded(false), 1800); } setAdding(false); } async function toggleWishlist() { if (wishlistLoading) return; const response = await fetch('/api/wishlist', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ productId: combo.id }) }); const data = await response.json(); if (response.ok) { setSaved(Boolean(data.saved)); window.dispatchEvent(new CustomEvent('wishlist-updated', { detail: { saved: Boolean(data.saved), count: data.count } })); } } return <article className={styles.productCard}><div className={styles.imageWrap}><span className={styles.discountBadge}>{combo.discount ? `-${combo.discount}%` : 'COMBO'}</span><button className={`${styles.wishlistButton} ${saved ? styles.saved : ''}`} type="button" onClick={toggleWishlist} disabled={wishlistLoading} aria-label={saved ? 'Remove from wishlist' : 'Add to wishlist'} aria-pressed={saved}><Heart size={17} fill={saved ? 'currentColor' : 'none'} /></button>{combo.image ? <img src={combo.image} alt={combo.name} /> : <span className={styles.imagePlaceholder}>Combo</span>}</div><div className={styles.cardBody}><span className={styles.cardCategory}>{combo.comboCategory} Combo</span><span className={styles.productName}>{combo.name}</span><span className={styles.itemCount}>{combo.itemCount} Items</span><span className={styles.rating}>★ {Number(combo.rating || 0).toFixed(1)} ({combo.reviewCount || 0})</span><div className={styles.priceRow}><strong>৳{combo.price.toLocaleString('en-IN')}</strong>{combo.oldPrice > combo.price && <del>৳{combo.oldPrice.toLocaleString('en-IN')}</del>}</div>{combo.savings > 0 && <span className={styles.savings}>You Save ৳{combo.savings.toLocaleString('en-IN')}</span>}<div className={styles.cardActions}><button type="button" className={styles.cartButton} onClick={addToCart} disabled={adding || Number(combo.stock || 0) <= 0}><ShoppingCart size={15} />{Number(combo.stock || 0) <= 0 ? 'Out of Stock' : added ? 'Added' : adding ? 'Adding...' : 'Add to Cart'}</button></div></div></article>; }
function EmptyState({ resetFilters }) { return <div className={styles.emptyState}><PackageCheck size={34} /><h2>কোনো কম্বো পণ্য পাওয়া যায়নি</h2><p>অন্য কোনো category বা price range দিয়ে আবার চেষ্টা করুন।</p><button type="button" onClick={resetFilters}><RotateCcw size={15} /> ফিল্টার রিসেট করুন</button></div>; }
function PromoBanners() { return <section className={styles.promoGrid}><div className={`${styles.promoBanner} ${styles.promoPrimary}`}><div><span className={styles.eyebrow}>SMART SHOPPING</span><h2>কষ্টা কিনুন, বেশি সাশ্রয় করুন!</h2><p>আমাদের বিশেষ কম্বো প্যাকেজে পাচ্ছেন সেরা পণ্য সেরা দামে।</p><Link href="#combo-categories">সব কম্বো দেখুন <ArrowRight size={15} /></Link></div><ShoppingBasket className={styles.basketArt} size={92} /></div><div className={`${styles.promoBanner} ${styles.promoOffer}`}><span className={styles.eyebrow}>COMBO OFFER!</span><h2>৳3,000+</h2><p>টাকার বেশি কম্বো কিনলে ফ্রি ডেলিভারি</p><strong>FREE<br />DELIVERY</strong></div><div className={`${styles.promoBanner} ${styles.promoWhy}`}><h2>Why Combo?</h2><p><Check size={14} /> একই প্যাকেজে বেশি পণ্য</p><p><Check size={14} /> বাজারের সেরা দাম</p><p><Check size={14} /> সময় ও টাকা দুটোই সাশ্রয়</p></div></section>; }
function ComboCategorySection({ setCategory }) { const cards = [{ name: 'Grocery Combo', value: 'Grocery', count: '5 Combos', icon: <ShoppingBasket size={18} /> }, { name: 'Family Combo', value: 'Family', count: '4 Combos', icon: <UsersRound size={18} /> }, { name: 'Ramadan Combo', value: 'Ramadan', count: '3 Combos', icon: <MoonStar size={18} /> }, { name: 'Bachelor Combo', value: 'Bachelor', count: '3 Combos', icon: <Home size={18} /> }, { name: 'Baby Care Combo', value: 'Baby Care', count: '2 Combos', icon: <Baby size={18} /> }]; return <section className={styles.categorySection} id="combo-categories"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>FIND YOUR FIT</span><h2>Shop Combo by Category</h2></div><Link href="/shop">View all <ArrowRight size={15} /></Link></div><div className={styles.categoryGrid}>{cards.map((item) => <button type="button" key={item.value} onClick={() => { setCategory(item.value); window.scrollTo({ top: 0, behavior: 'smooth' }); }}><span className={styles.categoryIcon}>{item.icon}</span><span><strong>{item.name}</strong><small>{item.count}</small></span><ChevronRight size={17} /></button>)}</div></section>; }
function TrustSection() { const items = [[ShieldCheck, '100% Authentic Products', 'নিশ্চিত মানের পণ্য'], [PackageCheck, 'Secure Payment', 'নিরাপদ পেমেন্ট সিস্টেম'], [RotateCcw, 'Easy Returns', 'সহজ রিটার্ন পলিসি'], [Search, 'Customer Support', '২৪/৭ কাস্টমার সেবা']]; return <section className={styles.trustSection}>{items.map(([Icon, title, text]) => <div key={title}><span><Icon size={19} /></span><p><strong>{title}</strong><small>{text}</small></p></div>)}</section>; }
function MobileFilterDrawer({ open, close, ...filterProps }) { return <><button className={`${styles.drawerBackdrop} ${open ? styles.show : ''}`} type="button" onClick={close} aria-label="Close filters" /><aside className={`${styles.mobileDrawer} ${open ? styles.drawerOpen : ''}`}><div className={styles.drawerHeader}><h2>Filter Combo</h2><button type="button" onClick={close} aria-label="Close filters"><X size={19} /></button></div><FilterOptions {...filterProps} /><button className={styles.applyButton} type="button" onClick={close}>Apply Filter <ArrowRight size={15} /></button></aside></>; }