'use client';
import OptimizedImage from '@/components/OptimizedImage';

import Link from 'next/link';
import { ArrowRight, Baby, Check, ChevronDown, ChevronRight, Heart, Home, Leaf, MoonStar, PackageCheck, RotateCcw, Search, ShieldCheck, ShoppingBag, ShoppingBasket, ShoppingCart, SlidersHorizontal, Truck, UsersRound, X } from 'lucide-react';
import { startTransition, useEffect, useMemo, useState } from 'react';
import { useCart } from '@/components/cart/CartProvider';
import { useWishlist } from '@/components/wishlist/WishlistProvider';
import styles from './ComboProductsPage.module.css';

const priceRanges = [{ label: '৳500 - ৳1,000', min: 500, max: 1000 }, { label: '৳1,000 - ৳2,000', min: 1000, max: 2000 }, { label: '৳2,000 - ৳3,000', min: 2000, max: 3000 }, { label: '৳3,000+', min: 3000, max: Infinity }];
function makeCombo(product) {
  const price = Number(product.salePrice || product.regularPrice || 0);
  const oldPrice = Number(product.regularPrice || 0);
  const itemCount = product.comboItems?.reduce((total, item) => total + Number(item.quantity || 1), 0) || 0;
  const discount = oldPrice > price ? Math.round(((oldPrice - price) / oldPrice) * 100) : 0;
  return { ...product, comboCategory: product.category?.name || 'Combo', brandName: (product.brandRelation?.name || product.brand || '').trim(), itemCount, price, oldPrice, discount, savings: Math.max(0, oldPrice - price), image: product.images?.[0]?.url || '' };
}

export default function ComboProductsPage({ products }) {
  const cart = useCart();
  const combos = useMemo(() => products.map(makeCombo), [products]);
  const [category, setCategory] = useState('All');
  const maxComboPrice = useMemo(() => Math.max(10000, ...combos.map((combo) => combo.price)), [combos]);
  const [priceLimit, setPriceLimit] = useState(maxComboPrice);
  const [sort, setSort] = useState('popular');
  const [sortMenuOpen, setSortMenuOpen] = useState(false);
  const [filterOpen, setFilterOpen] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [ratingFilter, setRatingFilter] = useState(0);
  const [availability, setAvailability] = useState('All');
  const categories = useMemo(() => Array.from(new Set(combos.map((combo) => combo.comboCategory).filter(Boolean))).sort((first, second) => first.localeCompare(second)).map((name) => ({ name, value: name, count: combos.filter((combo) => combo.comboCategory === name).length })), [combos]);
  const brands = useMemo(() => Array.from(new Set(combos.map((combo) => (combo.brandRelation?.name || combo.brand || '').trim()).filter(Boolean))).sort((first, second) => first.localeCompare(second)).map((name) => ({ name, value: name, count: combos.filter((combo) => (combo.brandRelation?.name || combo.brand || '').trim().toLowerCase() === name.toLowerCase()).length })), [combos]);
  const [brand, setBrand] = useState('All');
  useEffect(() => {
    if (!sortMenuOpen) return undefined;

    function handleClickOutside(event) {
      if (!event.target.closest('.combo-sort-control')) {
        setSortMenuOpen(false);
      }
    }

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [sortMenuOpen]);
  const visibleCombos = useMemo(() => {
    const filtered = combos.filter((combo) => (category === 'All' || combo.comboCategory === category) && (brand === 'All' || (combo.brandRelation?.name || combo.brand) === brand) && combo.price <= priceLimit && (!ratingFilter || Number(combo.rating || 0) >= ratingFilter) && (availability === 'All' || (availability === 'In stock' ? Number(combo.stock || 0) > 0 : Number(combo.stock || 0) < 1)));
    return [...filtered].sort((a, b) => sort === 'newest' ? String(b.id).localeCompare(String(a.id)) : sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : sort === 'discount' ? b.discount - a.discount : b.itemCount - a.itemCount);
  }, [availability, brand, category, combos, priceLimit, ratingFilter, sort]);
  useEffect(() => {
    startTransition(() => setCurrentPage(1));
  }, [availability, brand, category, priceLimit, ratingFilter, sort]);
  const totalPages = Math.max(1, Math.ceil(visibleCombos.length / 12));
  const pageCombos = visibleCombos.slice((currentPage - 1) * 12, currentPage * 12);
  function resetFilters() { setCategory('All'); setBrand('All'); setPriceLimit(maxComboPrice); setRatingFilter(0); setAvailability('All'); }
  const filterProps = { category, setCategory, categories, brand, setBrand, brands, priceLimit, maxComboPrice, setPriceLimit, ratingFilter, setRatingFilter, availability, setAvailability, resetFilters, close: () => setFilterOpen(false) };
  return <main className={styles.page}><div className={styles.pageShell}><Breadcrumb /><ComboPageHeader /><div className={styles.contentLayout}><FilterSidebar {...filterProps} /><section className={styles.results}><div className={styles.mobileToolbar}><button type="button" onClick={() => setFilterOpen(true)}><SlidersHorizontal size={16} /> Filter Combo</button><span>{visibleCombos.length} combos</span></div><ProductToolbar count={visibleCombos.length} sort={sort} setSort={setSort} sortMenuOpen={sortMenuOpen} setSortMenuOpen={setSortMenuOpen} />{pageCombos.length ? <div className={styles.productGrid}>{pageCombos.map((combo) => <ComboProductCard key={combo.id} combo={combo} cart={cart} />)}</div> : <EmptyState resetFilters={resetFilters} />}{totalPages > 1 && <div className={styles.pagination}><button type="button" disabled={currentPage === 1} onClick={() => setCurrentPage((page) => page - 1)}>Previous</button><span>Page {currentPage} of {totalPages}</span><button type="button" disabled={currentPage === totalPages} onClick={() => setCurrentPage((page) => page + 1)}>Next</button></div>}</section></div></div><MobileFilterDrawer open={filterOpen} close={() => setFilterOpen(false)} {...filterProps} /></main>;
}

function Breadcrumb() { return <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight size={13} /><span>Combo Products</span></nav>; }
function ComboPageHeader() { return <header className={styles.heroHeader}><div className={styles.heroCopy}><span className={styles.eyebrow}>SPECIAL DEALS</span><h1>Combo <strong>Products</strong></h1><p>Perfect combinations, better savings.<br />Get more with our exclusive combo deals!</p><Link className={styles.heroButton} href="#combo-categories">Shop Combos <ArrowRight size={16} /></Link></div><div className={styles.featureCards}><FeatureCard icon={<ShieldCheck size={19} />} title="Best Deals" text="Save More" /><FeatureCard icon={<Leaf size={19} />} title="Premium Quality" text="Trusted Products" /><FeatureCard icon={<Truck size={19} />} title="Fast Delivery" text="Across Bangladesh" /></div></header>; }
function FeatureCard({ icon, title, text }) { return <div className={styles.featureCard}><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>; }
function FilterSidebar(props) { return <>{props.mobile && <button className="shop-filter-backdrop" type="button" aria-label="Close filters" onClick={props.close} />}<aside className={`shop-filters ${props.mobile ? 'is-open' : ''}`}><div className="shop-filter-head"><h2>Filters</h2><button type="button" onClick={props.resetFilters}>Clear All</button><button className="shop-filter-close" type="button" onClick={props.close} aria-label="Close filters"><X size={19} /></button></div><ShopStyleFilterOptions {...props} />{props.mobile && <div className="shop-filter-actions"><button type="button" className="shop-filter-clear-btn" onClick={props.resetFilters}>Clear All</button><button type="button" className="shop-filter-apply-btn" onClick={props.close}>Apply Filters</button></div>}</aside></>; }
function ShopStyleFilterOptions({ category, setCategory, categories, brand, setBrand, brands, priceLimit, maxComboPrice, setPriceLimit, ratingFilter, setRatingFilter, availability, setAvailability }) { return <div><FilterSection title="Categories"><FilterRadio label={`All combos (${categories.reduce((total, item) => total + item.count, 0)})`} checked={category === 'All'} onChange={() => setCategory('All')} />{categories.map((item) => <FilterRadio key={item.value} label={`${item.name} (${item.count})`} checked={category === item.value} onChange={() => setCategory(item.value)} />)}</FilterSection>{brands.length > 0 && <FilterSection title="Brand"><FilterRadio label="All brands" checked={brand === 'All'} onChange={() => setBrand('All')} />{brands.map((item) => <FilterRadio key={item.value} label={`${item.name} (${item.count})`} checked={brand === item.name} onChange={() => setBrand(item.name)} />)}</FilterSection>}<section className="shop-filter-section combo-price-section"><h3>Price Range</h3><div className="combo-price-control"><input type="range" min="0" max={maxComboPrice} value={priceLimit} onChange={(event) => setPriceLimit(Number(event.target.value))} aria-label="Maximum combo price" /><div className="combo-price-values"><span>৳0</span><span>৳{priceLimit.toLocaleString('en-BD')}</span></div></div></section><FilterSection title="Rating"><FilterRadio label="All ratings" checked={ratingFilter === 0} onChange={() => setRatingFilter(0)} />{[5, 4, 3, 2, 1].map((rating) => <FilterRadio key={rating} label={`${'★'.repeat(rating)} & up`} checked={ratingFilter === rating} onChange={() => setRatingFilter(rating)} />)}</FilterSection><FilterSection title="Availability"><FilterRadio label="All products" checked={availability === 'All'} onChange={() => setAvailability('All')} /><FilterRadio label="In stock" checked={availability === 'In stock'} onChange={() => setAvailability('In stock')} /><FilterRadio label="Out of stock" checked={availability === 'Out of stock'} onChange={() => setAvailability('Out of stock')} /></FilterSection></div>; }
function FilterSection({ title, children }) { return <section className="shop-filter-section"><h3>{title}</h3><div>{children}</div></section>; }
function FilterRadio({ label, checked, onChange }) { return <label className="shop-filter-radio"><input type="radio" checked={checked} onChange={onChange} /><span>{label}</span></label>; }
function FilterOptions({ category, setCategory, categories, brand, setBrand, brands, selectedRanges, toggleRange, ratingFilter, setRatingFilter, availability, setAvailability }) { return <div className={styles.filterOptions}><div className={styles.filterGroup}><h3>Categories <ChevronDown size={14} /></h3><button type="button" className={category === 'All' ? styles.activeFilter : ''} onClick={() => setCategory('All')}><span>All Combos</span><small>{categories.reduce((total, item) => total + item.count, 0)}</small></button>{categories.map((item) => <button type="button" className={category === item.value ? styles.activeFilter : ''} key={item.value} onClick={() => setCategory(item.value)}><span>{item.name}</span><small>{item.count}</small></button>)}</div>{brands.length > 0 && <div className={styles.filterGroup}><h3>Brands <ChevronDown size={14} /></h3><select className={styles.filterSelect} value={brand} onChange={(event) => setBrand(event.target.value)}><option value="All">All Brands</option>{brands.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>}<div className={styles.filterGroup}><h3>Price Range <ChevronDown size={14} /></h3>{priceRanges.map((range) => <label key={range.label}><input type="checkbox" checked={selectedRanges.some((item) => item.min === range.min)} onChange={() => toggleRange(range)} /><span>{range.label}</span></label>)}</div><div className={styles.filterGroup}><h3>Rating <ChevronDown size={14} /></h3>{[4, 3, 2].map((rating) => <button type="button" className={ratingFilter === rating ? styles.activeFilter : ''} key={rating} onClick={() => setRatingFilter(rating)}><span>★ {rating}+ rating</span></button>)}</div><div className={styles.filterGroup}><h3>Availability <ChevronDown size={14} /></h3>{['All', 'In stock', 'Out of stock'].map((value) => <button type="button" className={availability === value ? styles.activeFilter : ''} key={value} onClick={() => setAvailability(value)}><span>{value}</span></button>)}</div></div>; }
function ProductToolbar({ count, sort, setSort, sortMenuOpen, setSortMenuOpen }) { const sortOptions = [{ value: 'popular', label: 'Popularity' }, { value: 'newest', label: 'Newest' }, { value: 'low', label: 'Price: Low to High' }, { value: 'high', label: 'Price: High to Low' }, { value: 'discount', label: 'Discount' }]; const selectedSort = sortOptions.find((option) => option.value === sort)?.label || 'Popularity'; return <div className={styles.productToolbar}><span>Showing {count} combo products</span><div className={`shop-toolbar-sort combo-sort-control ${sortMenuOpen ? 'is-open' : ''}`}><button type="button" className="shop-sort-trigger" onClick={() => setSortMenuOpen((open) => !open)} aria-haspopup="listbox" aria-expanded={sortMenuOpen} aria-label="Sort combo products"><span className="shop-sort-label">Sort by</span><span className="shop-sort-value">{selectedSort}</span><span className="shop-sort-icon"><ChevronDown size={16} /></span></button>{sortMenuOpen && <div className="shop-sort-menu" role="listbox" aria-label="Combo sort options">{sortOptions.map((option) => <button key={option.value} type="button" role="option" className={`shop-sort-option ${sort === option.value ? 'is-selected' : ''}`} onClick={() => { setSort(option.value); setSortMenuOpen(false); }} aria-selected={sort === option.value}><span>{option.label}</span>{sort === option.value && <span className="shop-sort-dot" aria-hidden="true" />}</button>)}</div>}</div></div>; }
function ComboProductCard({ combo, cart }) { const wishlist = useWishlist(); const saved = wishlist?.isSaved(combo.id) || false; const wishlistLoading = !wishlist?.ready; const [added, setAdded] = useState(false); const [adding, setAdding] = useState(false); async function addToCart() { if (adding || Number(combo.stock || 0) <= 0) return; setAdding(true); const result = await cart.add(combo); if (result?.ok) { setAdded(true); window.setTimeout(() => setAdded(false), 1800); } setAdding(false); } async function toggleWishlist() { if (wishlistLoading) return; try { await wishlist.toggle(combo.id); } catch {} } return <article className={styles.productCard}><div className={styles.imageWrap}><span className={styles.discountBadge}>{combo.discount ? `-${combo.discount}%` : 'COMBO'}</span><button className={`${styles.wishlistButton} ${saved ? styles.saved : ''}`} type="button" onClick={toggleWishlist} disabled={wishlistLoading} aria-label={saved ? 'Remove from wishlist' : 'Add to wishlist'} aria-pressed={saved}><Heart size={17} fill={saved ? 'currentColor' : 'none'} /></button>{combo.image ? <OptimizedImage src={combo.image} alt={combo.name} /> : <span className={styles.imagePlaceholder}>Combo</span>}</div><div className={styles.cardBody}><span className={styles.cardCategory}>{combo.comboCategory} Combo</span><span className={styles.productName}>{combo.name}</span><span className={styles.itemCount}>{combo.itemCount} Items</span><span className={styles.rating}>★ {Number(combo.rating || 0).toFixed(1)} ({combo.reviewCount || 0})</span><div className={styles.priceRow}><strong>৳{combo.price.toLocaleString('en-IN')}</strong>{combo.oldPrice > combo.price && <del>৳{combo.oldPrice.toLocaleString('en-IN')}</del>}</div>{combo.savings > 0 && <span className={styles.savings}>You Save ৳{combo.savings.toLocaleString('en-IN')}</span>}<div className={styles.cardActions}><button type="button" className={styles.cartButton} onClick={addToCart} disabled={adding || Number(combo.stock || 0) <= 0}><ShoppingCart size={15} />{Number(combo.stock || 0) <= 0 ? 'Out of Stock' : added ? 'Added' : adding ? 'Adding...' : 'Add to Cart'}</button></div></div></article>; }
function EmptyState({ resetFilters }) { return <div className={styles.emptyState}><PackageCheck size={34} /><h2>কোনো কম্বো পণ্য পাওয়া যায়নি</h2><p>অন্য কোনো category বা price range দিয়ে আবার চেষ্টা করুন।</p><button type="button" onClick={resetFilters}><RotateCcw size={15} /> ফিল্টার রিসেট করুন</button></div>; }
function PromoBanners() { return <section className={styles.promoGrid}><div className={`${styles.promoBanner} ${styles.promoPrimary}`}><div><span className={styles.eyebrow}>SMART SHOPPING</span><h2>কষ্টা কিনুন, বেশি সাশ্রয় করুন!</h2><p>আমাদের বিশেষ কম্বো প্যাকেজে পাচ্ছেন সেরা পণ্য সেরা দামে।</p><Link href="#combo-categories">সব কম্বো দেখুন <ArrowRight size={15} /></Link></div><ShoppingBasket className={styles.basketArt} size={92} /></div><div className={`${styles.promoBanner} ${styles.promoOffer}`}><span className={styles.eyebrow}>COMBO OFFER!</span><h2>৳3,000+</h2><p>টাকার বেশি কম্বো কিনলে ফ্রি ডেলিভারি</p><strong>FREE<br />DELIVERY</strong></div><div className={`${styles.promoBanner} ${styles.promoWhy}`}><h2>Why Combo?</h2><p><Check size={14} /> একই প্যাকেজে বেশি পণ্য</p><p><Check size={14} /> বাজারের সেরা দাম</p><p><Check size={14} /> সময় ও টাকা দুটোই সাশ্রয়</p></div></section>; }
function ComboCategorySection({ setCategory }) { const cards = [{ name: 'Grocery Combo', value: 'Grocery', count: '5 Combos', icon: <ShoppingBasket size={18} /> }, { name: 'Family Combo', value: 'Family', count: '4 Combos', icon: <UsersRound size={18} /> }, { name: 'Ramadan Combo', value: 'Ramadan', count: '3 Combos', icon: <MoonStar size={18} /> }, { name: 'Bachelor Combo', value: 'Bachelor', count: '3 Combos', icon: <Home size={18} /> }, { name: 'Baby Care Combo', value: 'Baby Care', count: '2 Combos', icon: <Baby size={18} /> }]; return <section className={styles.categorySection} id="combo-categories"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>FIND YOUR FIT</span><h2>Shop Combo by Category</h2></div><Link href="/shop">View all <ArrowRight size={15} /></Link></div><div className={styles.categoryGrid}>{cards.map((item) => <button type="button" key={item.value} onClick={() => { setCategory(item.value); window.scrollTo({ top: 0, behavior: 'smooth' }); }}><span className={styles.categoryIcon}>{item.icon}</span><span><strong>{item.name}</strong><small>{item.count}</small></span><ChevronRight size={17} /></button>)}</div></section>; }
function TrustSection() { const items = [[ShieldCheck, '100% Authentic Products', 'নিশ্চিত মানের পণ্য'], [PackageCheck, 'Secure Payment', 'নিরাপদ পেমেন্ট সিস্টেম'], [RotateCcw, 'Easy Returns', 'সহজ রিটার্ন পলিসি'], [Search, 'Customer Support', '২৪/৭ কাস্টমার সেবা']]; return <section className={styles.trustSection}>{items.map(([Icon, title, text]) => <div key={title}><span><Icon size={19} /></span><p><strong>{title}</strong><small>{text}</small></p></div>)}</section>; }
function MobileFilterDrawer({ open, close, ...filterProps }) { if (!open) return null; return <FilterSidebar {...filterProps} mobile close={close} />; }