import Link from 'next/link';
import { prisma } from '@/lib/prisma';

export default async function Marketing() {
  const [coupons, banners] = await Promise.all([
    prisma.coupon.findMany({ orderBy: { code: 'asc' }, take: 8 }),
    prisma.banner.findMany({ orderBy: { sortOrder: 'asc' }, take: 8 }),
  ]);
  const safeCoupons = coupons.map(coupon => ({ id: coupon.id, code: coupon.code, type: coupon.type, value: Number(coupon.value), active: coupon.active }));
  const activeCoupons = safeCoupons.filter(coupon => coupon.active).length;
  const activeBanners = banners.filter(banner => banner.active).length;
  return <>
    <div className="admin-page-heading"><div><div className="eyebrow">Growth</div><h1>Marketing</h1><p className="muted">Manage promotions already connected to your store.</p></div><Link className="btn" href="/admin/coupons">Create coupon</Link></div>
    <div className="stat-grid"><div className="stat"><span className="muted">Active coupons</span><strong>{activeCoupons}</strong><small className="positive">Live promotions</small></div><div className="stat"><span className="muted">Active banners</span><strong>{activeBanners}</strong><small className="muted">Homepage placements</small></div><div className="stat"><span className="muted">Subscribers</span><strong>N/A</strong><small className="muted">Newsletter table unavailable</small></div><div className="stat"><span className="muted">Campaigns</span><strong>N/A</strong><small className="muted">No live campaign persistence</small></div></div>
    <div className="admin-dashboard-grid marketing-dashboard-grid"><section className="section marketing-panel"><div className="section-head"><div><div className="section-kicker">COUPONS</div><h2>Promotions</h2><p className="muted">Existing coupon codes</p></div><Link href="/admin/coupons">Manage</Link></div><div className="admin-table-wrap marketing-table-wrap"><table className="table marketing-table"><thead><tr><th>Code</th><th>Type</th><th>Value</th><th>Status</th></tr></thead><tbody>{safeCoupons.map(coupon => <tr key={coupon.id}><td><span className="marketing-code">{coupon.code}</span></td><td><span className="marketing-type">{coupon.type === 'PERCENTAGE' ? 'Percentage' : 'Fixed amount'}</span></td><td><strong className="marketing-value">{coupon.type === 'PERCENTAGE' ? `${coupon.value}%` : `৳${coupon.value}`}</strong></td><td><span className={coupon.active ? 'status active' : 'status'}>{coupon.active ? 'Active' : 'Inactive'}</span></td></tr>)}</tbody></table>{!safeCoupons.length && <p className="muted marketing-empty">No coupons yet.</p>}</div></section><section className="section marketing-panel"><div className="section-head"><div><div className="section-kicker">PLACEMENTS</div><h2>Promotional banners</h2><p className="muted">Existing banner placements</p></div><Link href="/admin/banners">Manage</Link></div><div className="marketing-banner-table"><div className="marketing-banner-row marketing-banner-head"><span>Banner</span><span>Destination</span><span>Status</span></div>{banners.map(banner => <div className="marketing-banner-row" key={banner.id}><span><strong>{banner.title || 'Homepage banner'}</strong><small>Priority #{Number(banner.sortOrder) + 1}</small></span><span className="marketing-destination">{banner.link || 'No destination link'}</span><span className={banner.active ? 'positive' : 'muted'}>{banner.active ? 'Live' : 'Off'}</span></div>)}</div>{!banners.length && <p className="muted marketing-empty">No banners yet.</p>}</section></div>
  </>;
}
