import Link from 'next/link';
import styles from './TermsConditions.module.css';

export const metadata = {
  title: 'Terms & Conditions | Prenaxo',
  description: "Read Prenaxo's Terms & Conditions covering orders, payments, delivery, returns, refunds, accounts and website usage.",
};

const sections = [
  ['acceptance', 'Acceptance of Terms'], ['about', 'About Prenaxo'], ['eligibility', 'Eligibility and User Responsibility'], ['account', 'Customer Account'], ['products', 'Products and Product Information'], ['prices', 'Product Prices'], ['availability', 'Product Availability'], ['placement', 'Order Placement'], ['confirmation', 'Order Confirmation'], ['cancellation', 'Order Cancellation'], ['payment', 'Payment'], ['delivery', 'Delivery and Shipping'], ['receiving', 'Receiving an Order'], ['returns', 'Returns'], ['refunds', 'Refunds'], ['exchange', 'Exchange / Replacement'], ['reviews', 'Customer Reviews'], ['prohibited-use', 'Prohibited Use'], ['intellectual-property', 'Intellectual Property'], ['third-party-services', 'Third-Party Services'], ['availability-of-site', 'Website Availability'], ['limitation', 'Limitation of Liability'], ['force-majeure', 'Force Majeure'], ['privacy', 'Privacy'], ['changes', 'Changes to Terms'], ['governing-law', 'Governing Law'], ['customer-rights', 'Customer Rights'], ['contact', 'Contact Us'],
];

function Section({ id, title, children }) { return <section className={styles.section} id={id}><h2>{title}</h2>{children}</section>; }
function List({ children }) { return <ul className={styles.list}>{children}</ul>; }
function BusinessDetails() { return <div className={styles.contactCard}><strong>Prenaxo</strong><span>Phone: <a href="tel:01608069154">01608069154</a></span><span>Address: Asim, Fulbaria, Mymensingh, Bangladesh</span></div>; }

export default function Terms() {
  return <main className={styles.page}>
    <div className={styles.hero}><span className={styles.eyebrow}>Prenaxo</span><h1>Terms &amp; Conditions</h1><p className={styles.updated}>Last Updated: September 5, 2026</p><p className={styles.lead}>Please read these Terms &amp; Conditions carefully before using Prenaxo or placing an order. By accessing or using Prenaxo, you agree to these Terms &amp; Conditions. If you do not agree, please do not use the website.</p></div>
    <div className={styles.layout}>
      <aside className={styles.toc} aria-label="Terms and conditions contents"><strong>On this page</strong><nav>{sections.map(([id, title], index) => <a href={`#${id}`} key={id}><span>{index + 1}</span>{title}</a>)}</nav></aside>
      <article className={styles.content}>
        <Section id="acceptance" title="1. Acceptance of Terms"><p>By visiting or using Prenaxo, you agree to these Terms. They apply to browsing, accounts, shopping, ordering, checkout, and related services. Prenaxo may update these Terms when necessary. If you do not agree with an updated version, you should stop using the website.</p></Section>
        <Section id="about" title="2. About Prenaxo"><p>Prenaxo is an online eCommerce platform serving customers in Bangladesh.</p><BusinessDetails /></Section>
        <Section id="eligibility" title="3. Eligibility and User Responsibility"><p>Customers are responsible for providing accurate information, a valid delivery address, and a reachable phone number. Customers must keep account information secure, use the website lawfully, and must not abuse website functionality.</p></Section>
        <Section id="account" title="4. Customer Account"><p>Some features may require an account. You must provide accurate information and keep your credentials secure. Do not share your password, and notify Prenaxo if you suspect unauthorized access. Prenaxo may restrict or suspend an account where reasonably necessary for security, fraud prevention, or serious policy violations.</p></Section>
        <Section id="products" title="5. Products and Product Information"><p>Prenaxo tries to provide accurate product names, descriptions, images, prices, availability, and specifications. Minor differences may occur between displayed images and actual products where appropriate. Product information should not be misleading. If a product is unavailable, Prenaxo may need to cancel or modify the affected order and inform the customer.</p></Section>
        <Section id="prices" title="6. Product Prices"><p>Product prices are displayed on the website and may change from time to time. The applicable price is generally the price shown at the time of order or checkout, subject to legitimate correction of obvious errors. Delivery charges and other applicable charges are shown before order completion where available. If an obvious technical or pricing error occurs, Prenaxo may contact the customer to confirm or cancel the affected order.</p></Section>
        <Section id="availability" title="7. Product Availability"><p>Orders are subject to product availability. If a product becomes unavailable before fulfillment, Prenaxo may contact the customer and remove or cancel the affected item. Any applicable refund will be handled according to the circumstances and applicable refund procedure.</p></Section>
        <Section id="placement" title="8. Order Placement"><p>The checkout process generally involves:</p><ol className={styles.list}><li>Selecting products.</li><li>Adding products to the cart.</li><li>Providing contact and delivery information.</li><li>Selecting a payment method.</li><li>Reviewing the order and placing it.</li><li>Prenaxo processing the order.</li></ol><p>Placing an order does not necessarily guarantee fulfillment until it is accepted or confirmed through the applicable business process.</p></Section>
        <Section id="confirmation" title="9. Order Confirmation"><p>Prenaxo may verify an order before fulfillment. Verification may involve phone confirmation, address verification, stock verification, payment verification, or fraud and security checks. If an order cannot be fulfilled, Prenaxo will notify the customer where reasonably possible.</p></Section>
        <Section id="cancellation" title="10. Order Cancellation"><p>An order may need to be cancelled for legitimate operational reasons, including product unavailability, incorrect product information, an obvious pricing or technical error, a customer cancellation request where cancellation is still possible, suspicious order activity, or invalid delivery information. If payment has already been received, any applicable refund will follow the relevant refund procedure. These Terms do not limit rights that cannot legally be excluded.</p></Section>
        <Section id="payment" title="11. Payment"><p>The checkout currently supports:</p><List><li><strong>Cash on Delivery:</strong> payment when the order is delivered.</li><li><strong>bKash / Nagad:</strong> mobile banking payment using the checkout instructions and transaction ID.</li><li><strong>Bank Payment:</strong> bank payment details provided by the Prenaxo team after placing the order.</li></List><p>Customers must provide accurate payment information where required. Payment confirmation may be required before processing. Third-party payment providers may have their own terms. Prenaxo does not ask customers to share passwords, PINs, or unnecessary security credentials.</p></Section>
        <Section id="delivery" title="12. Delivery and Shipping"><p>Customers must provide an accurate delivery address and reachable phone number. Standard delivery cost is calculated from the selected delivery division and district using Prenaxo&apos;s active delivery zones. Free delivery applies when the order reaches the threshold shown during checkout; the threshold is loaded from the website&apos;s delivery configuration. Delivery timing may vary with location, product availability, and logistics. Delivery charges, where applicable, are shown during checkout, and delays may occur because of circumstances outside reasonable control.</p></Section>
        <Section id="receiving" title="13. Receiving an Order"><p>Customers should check the package when receiving it, verify the product and quantity, and report damaged, incorrect, or missing items as soon as reasonably possible. Any return or refund request remains subject to the applicable circumstances and Prenaxo&apos;s available support process.</p></Section>
        <Section id="returns" title="14. Returns"><p>Prenaxo does not currently publish a separate return-policy route in the website application. Return requests, where applicable, should be raised with Prenaxo using the contact information below and will be reviewed according to the order status, product condition, and circumstances of the request. Customers should keep order information and relevant product packaging where possible.</p></Section>
        <Section id="refunds" title="15. Refunds"><p>There is no separate refund-policy route currently published in the website application. Approved refunds, where applicable, are reviewed according to the payment method, order status, cancellation or product issue, and the applicable refund procedure. Contact Prenaxo for order-specific guidance; no specific refund timeline is promised by these Terms.</p></Section>
        <Section id="exchange" title="16. Exchange / Replacement"><p>Prenaxo does not currently state a general exchange program in the available website implementation. If a product issue may require replacement or another resolution, contact Prenaxo with the order details so the request can be reviewed.</p></Section>
        <Section id="reviews" title="17. Customer Reviews"><p>The website allows customers to submit product reviews. Reviews must be relevant and must not contain:</p><List><li>Fake, misleading, or spam content.</li><li>Abusive content, hate speech, or illegal content.</li><li>Personal information belonging to another person.</li><li>Promotional spam or content unrelated to the product.</li></List><p>Reviews are subject to the website&apos;s approval process, and Prenaxo may remove content that violates applicable rules. Prenaxo does not claim that every review is independently verified.</p></Section>
        <Section id="prohibited-use" title="18. Prohibited Use"><p>Customers must not use Prenaxo to commit fraud, place intentionally false orders, abuse promotions, attempt unauthorized access, interfere with website functionality, upload malicious code, scrape or misuse website data, impersonate another person, violate applicable law, or abuse customer support or delivery personnel.</p></Section>
        <Section id="intellectual-property" title="19. Intellectual Property"><p>Unless otherwise stated, Prenaxo branding, logo, website design, text, product content, graphics, UI elements, and original website materials may be protected by applicable intellectual property laws. Customers may not copy, reproduce, modify, distribute, or commercially exploit Prenaxo&apos;s original content without permission, except where permitted by law.</p></Section>
        <Section id="third-party-services" title="20. Third-Party Services"><p>Prenaxo may rely on third-party services that support payment processing, delivery or logistics, hosting, and website technology. These services may have separate terms and privacy policies. Prenaxo does not add a specific external analytics service to these Terms because no such service is currently identified in the project.</p></Section>
        <Section id="availability-of-site" title="21. Website Availability"><p>Prenaxo aims to keep the website available and functional, but temporary interruptions may occur because of maintenance, technical or hosting problems, network problems, security incidents, or events outside reasonable control. Continuous or uninterrupted availability is not guaranteed.</p></Section>
        <Section id="limitation" title="22. Limitation of Liability"><p>Prenaxo is not responsible for temporary website interruptions, failures of third-party services, events outside reasonable control, or problems caused by incorrect information supplied by a customer, to the extent permitted by applicable law. Nothing in these Terms is intended to exclude or limit customer rights that cannot legally be excluded.</p></Section>
        <Section id="force-majeure" title="23. Force Majeure / Events Outside Control"><p>Order or delivery delays may occur because of natural disasters, severe weather, transport disruptions, public emergencies, infrastructure failures, major technical outages, or other events beyond reasonable control. This clause does not remove legitimate customer obligations or applicable customer rights.</p></Section>
        <Section id="privacy" title="24. Privacy"><p>Customer information is handled according to the <Link href="/privacy">Prenaxo Privacy Policy</Link>. The Privacy Policy explains information collection, use, sharing, security, cookies, and customer privacy choices.</p></Section>
        <Section id="changes" title="25. Changes to Terms"><p>Prenaxo may update these Terms &amp; Conditions from time to time and will update the Last Updated date when a revised version is published. Continued use of the website after an update may indicate acceptance where appropriate, but mandatory legal rights remain unaffected.</p></Section>
        <Section id="governing-law" title="26. Governing Law"><p>These Terms are intended to operate subject to the applicable laws of Bangladesh. No particular court jurisdiction is specified by these Terms.</p></Section>
        <Section id="customer-rights" title="27. Customer Rights"><p>Nothing in these Terms is intended to remove rights that customers have under applicable law. Customers may contact Prenaxo regarding orders, delivery, returns, refunds, product issues, account issues, or questions about these Terms.</p></Section>
        <Section id="contact" title="28. Contact Us"><p>For questions regarding these Terms &amp; Conditions, contact Prenaxo using the available information:</p><BusinessDetails /></Section>
      </article>
    </div>
  </main>;
}