import { prisma } from '@/lib/prisma';

export const DEFAULT_PAYMENT_METHODS = [
  {
    code: 'COD',
    name: 'Cash on Delivery',
    type: 'COD',
    description: 'Pay for your order when it is delivered to your address.',
    logoUrl: null,
    requiresTransactionId: false,
    accountNumber: null,
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions:
      'You can pay cash when your order is delivered to your address.',
    active: true,
    sortOrder: 1,
  },

  {
    code: 'BKASH',
    name: 'bKash',
    type: 'MANUAL_WALLET',
    description: 'Send payment using bKash and enter your transaction ID.',
    logoUrl: 'https://res.cloudinary.com/ethp0qrs/image/upload/v1790904746/bkash-logo-horizontal-bangla-mobile-banking-app-icon-free-png.png',
    requiresTransactionId: true,
    accountNumber: '01608069154',
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions:
      'Send the payment to the bKash number above and enter your transaction ID before placing the order.',
    active: true,
    sortOrder: 2,
  },

  {
    code: 'NAGAD',
    name: 'Nagad',
    type: 'MANUAL_WALLET',
    description: 'Send payment using Nagad and enter your transaction ID.',
    logoUrl: 'https://res.cloudinary.com/ethp0qrs/image/upload/v1790904660/Nagad-Logo.wine.png',
    requiresTransactionId: true,
    accountNumber: '01608069154',
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions:
      'Send the payment to the Nagad number above and enter your transaction ID before placing the order.',
    active: true,
    sortOrder: 3,
  },

  {
    code: 'BANK',
    name: 'Bank Payment',
    type: 'BANK_TRANSFER',
    description: 'Pay through bank transfer.',
    logoUrl: null,
    requiresTransactionId: false,
    accountNumber: null,
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions:
      'Our team will contact you with bank payment details after placing your order.',
    active: true,
    sortOrder: 4,
  },
  {
    code: 'ROCKET',
    name: 'Rocket',
    type: 'MANUAL_WALLET',
    description: 'Send payment using Rocket and enter your transaction ID.',
    logoUrl: 'https://res.cloudinary.com/ethp0qrs/image/upload/v1790905387/rocket-color-logo-mobile-banking-icon-free-png.png',
    requiresTransactionId: true,
    accountNumber: null,
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions: 'Add the Rocket account number in admin settings before enabling this method.',
    active: false,
    sortOrder: 5,
  },
  {
    code: 'SSLCOMMERZ',
    name: 'Online payment',
    type: 'GATEWAY',
    description: 'Pay securely through the hosted payment page.',
    logoUrl: null,
    requiresTransactionId: false,
    gatewayProvider: 'SSLCOMMERZ',
    gatewayChannel: null,
    accountNumber: null,
    accountName: null,
    bankName: null,
    branchName: null,
    routingNumber: null,
    instructions: 'You will be redirected to the secure payment page.',
    active: false,
    sortOrder: 10,
  },
];

export async function ensureDefaultPaymentMethods(db = prisma) {
  return db.paymentMethod.createMany({
    data: DEFAULT_PAYMENT_METHODS,
    skipDuplicates: true,
  });
}
