import OptimizedImage from '@/components/OptimizedImage';
import Link from 'next/link';
import { ArrowDownRight, ArrowUpRight, BarChart3, Boxes, CircleDollarSign, MapPinned, Package, RefreshCw, ShoppingCart, Sparkles, Users } from 'lucide-react';
import styles from './AnalyticsReport.module.css';

const categoryColors = ['var(--brand-primary)', 'var(--brand-secondary)', 'var(--brand-primary)', 'var(--brand-accent)', 'var(--brand-secondary)', 'var(--brand-accent)'];

function number(value) { return Number(value || 0).toLocaleString(); }
function money(value) { return `৳${number(value)}`; }
function changeLabel(value) { return value === null || value === undefined ? 'No baseline' : `${value >= 0 ? '+' : ''}${value}%`; }
function statusClass(status) { return styles[`status${String(status).toLowerCase()}`] || styles.statusDefault; }
function stockLabel(product) { return product.stock === 0 ? 'Out of stock' : product.stock <= product.lowStock ? 'Low stock' : 'In stock'; }

function chartPoints(data, key, max) {
  const width = 760;
  const height = 220;
  const step = data.length > 1 ? 728 / (data.length - 1) : 0;
  return data.map((item, index) => `${18 + index * step},${height - 28 - ((Number(item[key] || 0) / Math.max(max, 1)) * 174)}`).join(' ');
}

function EmptyState({ children }) { return <div className={styles.empty}>{children}</div>; }

function SectionHeading({ eyebrow, title, action }) {
  return <div className={styles.sectionHeading}><div>{eyebrow && <span className={styles.eyebrow}>{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>;
}

function MetricCard({ icon: Icon, label, value, change, comparison, tone }) {
  const positive = change !== null && change !== undefined && change >= 0;
  return <article className={`${styles.metricCard} ${styles[`tone${tone}`]}`}><div className={styles.metricTop}><span className={styles.metricIcon}><Icon size={18} strokeWidth={2.2} /></span><span className={styles.metricLabel}>{label}</span></div><strong className={styles.metricValue}>{value}</strong><div className={styles.metricFoot}>{change === null || change === undefined ? <span className={styles.neutralChange}>No baseline</span> : <span className={positive ? styles.positiveChange : styles.negativeChange}>{positive ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{changeLabel(change)}</span>}<span>{comparison}</span></div></article>;
}

export default function AnalyticsReport({ summary, daily = [], topProducts = [], categorySales = [], orderStatus = [], productPerformance = [], geographicSales = [], comboProducts = [], insights = [], range, rangeLabel, filters, filterOptions }) {
  const maxRevenue = Math.max(...daily.map((item) => item.revenue), 1);
  const maxOrders = Math.max(...daily.map((item) => item.orders), 1);
  const categoryTotal = categorySales.reduce((total, item) => total + Number(item.revenue || 0), 0);
  const chartLabelStep = Math.max(1, Math.ceil(daily.length / 7));
  const cards = [
    { icon: CircleDollarSign, label: 'Total revenue', value: money(summary.revenue), change: summary.changes.revenue, tone: 'Blue' },
    { icon: ShoppingCart, label: 'Total orders', value: number(summary.orders), change: summary.changes.orders, tone: 'Green' },
    { icon: Users, label: 'Customers', value: number(summary.customers), change: summary.changes.customers, tone: 'Purple' },
    { icon: Boxes, label: 'Products sold', value: number(summary.units), change: summary.changes.units, tone: 'Orange' },
    { icon: BarChart3, label: 'Average order value', value: money(summary.average), change: summary.changes.average, tone: 'Teal' },
  ];

  return <main className={styles.analytics}>
    <div className={styles.pageHeader}><div><span className={styles.eyebrow}>Performance overview</span><h1>Analytics</h1><p>Live reporting from paid orders and catalogue data.</p></div><form className={styles.rangeForm} method="get" action="/admin/analytics"><label htmlFor="range">Reporting period</label><select id="range" name="range" defaultValue={range}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7days">Last 7 days</option><option value="30days">Last 30 days</option><option value="90days">Last 90 days</option><option value="this-month">This month</option><option value="last-month">Last month</option><option value="custom">Custom range</option></select><input type="date" name="from" defaultValue={filters.from} aria-label="From date" /><span className={styles.rangeDash}>to</span><input type="date" name="to" defaultValue={filters.to} aria-label="To date" /><button type="submit">Apply</button></form></div>
    <div className={styles.periodNote}><span>{rangeLabel}</span><span>Compared with the immediately preceding period</span></div>
    <section className={styles.metricGrid} aria-label="Summary metrics">{cards.map((card) => <MetricCard key={card.label} {...card} comparison="vs previous period" />)}</section>

    <section className={`${styles.panel} ${styles.overviewPanel}`}><SectionHeading eyebrow="Revenue overview" title="Revenue and orders" action={<span className={styles.panelPeriod}>{rangeLabel}</span>} /><div className={styles.chartTotals}><div><span>Revenue</span><strong>{money(summary.revenue)}</strong></div><div><span>Orders</span><strong>{number(summary.orders)}</strong></div><div><span>Profit</span><strong>{summary.profit === null ? 'Not available' : money(summary.profit)}</strong></div></div>{daily.length ? <div className={styles.chartWrap}><svg className={styles.lineChart} viewBox="0 0 760 250" role="img" aria-label="Revenue and order trend"><line className={styles.gridLine} x1="18" x2="746" y1="192" y2="192" /><line className={styles.gridLine} x1="18" x2="746" y1="105" y2="105" /><polyline className={styles.revenueLine} points={chartPoints(daily, 'revenue', maxRevenue)} /><polyline className={styles.ordersLine} points={chartPoints(daily, 'orders', maxOrders)} />{daily.map((item, index) => index % chartLabelStep === 0 || index === daily.length - 1 ? <text key={item.label + index} className={styles.chartLabel} x={daily.length > 1 ? 18 + index * (728 / (daily.length - 1)) : 18} y="228">{item.shortLabel}</text> : null)}</svg><div className={styles.legend}><span><i className={styles.revenueSwatch} />Revenue</span><span><i className={styles.ordersSwatch} />Orders</span></div></div> : <EmptyState>No sales yet.</EmptyState>}</section>

    <div className={styles.twoColumn}><section className={styles.panel}><SectionHeading eyebrow="Category mix" title="Sales by category" />{categorySales.length ? <div className={styles.categoryLayout}><div className={styles.donut} style={{ background: `conic-gradient(${categorySales.map((item, index) => { const start = categorySales.slice(0, index).reduce((total, category) => total + (categoryTotal ? category.revenue / categoryTotal : 0) * 100, 0); const end = start + (categoryTotal ? item.revenue / categoryTotal : 0) * 100; return `${categoryColors[index % categoryColors.length]} ${start}% ${end}%`; }).join(', ')})` }}><div>{money(categoryTotal)}<small>revenue</small></div></div><div className={styles.categoryLegend}>{categorySales.slice(0, 6).map((item, index) => <div key={item.name} className={styles.legendRow}><span><i style={{ background: categoryColors[index % categoryColors.length] }} />{item.name}</span><strong>{item.percentage}%</strong></div>)}</div></div> : <EmptyState>No category sales yet.</EmptyState>}</section><section className={styles.panel}><SectionHeading eyebrow="Fulfilment" title="Order status overview" />{orderStatus.length ? <div className={styles.statusList}>{orderStatus.map((item) => <div className={styles.statusRow} key={item.status}><div className={styles.statusMeta}><span>{item.label}</span><strong>{number(item.count)}</strong></div><div className={styles.progress}><span className={statusClass(item.status)} style={{ width: `${Math.min(item.percentage, 100)}%` }} /></div><small>{item.percentage}% of orders</small></div>)}</div> : <EmptyState>No orders in this period.</EmptyState>}</section></div>

    <section className={styles.panel}><SectionHeading eyebrow="Product performance" title="Top selling products" action={<Link className={styles.textLink} href="/admin/products">View all products</Link>} />{topProducts.length ? <div className={styles.productTableWrap}><table className={styles.productTable}><thead><tr><th>Product</th><th>Sold</th><th>Revenue</th><th>Stock</th><th>Performance</th></tr></thead><tbody>{topProducts.map((product) => <tr key={product.id}><td><div className={styles.productCell}><div className={styles.productImage}>{product.image ? <OptimizedImage src={product.image} alt={product.imageAlt} /> : <Package size={17} />}</div><div><strong>{product.name}</strong><small>{product.category}</small></div></div></td><td>{number(product.quantity)}</td><td>{money(product.revenue)}</td><td><span className={styles.stockPill}>{stockLabel(product)}</span><small className={styles.stockNumber}>{number(product.stock)}</small></td><td><span className={styles.performance}>{product.performance || 'Average'}</span></td></tr>)}</tbody></table></div> : <EmptyState>No products sold yet.</EmptyState>}</section>

    <section className={styles.panel}><SectionHeading eyebrow="Catalogue filters" title="Product performance" /><form className={styles.filterForm} method="get" action="/admin/analytics"><input type="hidden" name="range" value={range} /><input type="hidden" name="from" value={filters.from} /><input type="hidden" name="to" value={filters.to} /><label>Category<select name="categoryId" defaultValue={filters.categoryId}><option value="">All categories</option>{filterOptions.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Brand<select name="brandId" defaultValue={filters.brandId}><option value="">All brands</option>{filterOptions.brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><label>Stock status<select name="stockStatus" defaultValue={filters.stockStatus}><option value="all">All stock</option><option value="in">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></label><button type="submit">Filter results</button></form>{productPerformance.length ? <div className={styles.productTableWrap}><table className={styles.productTable}><thead><tr><th>Product</th><th>Category</th><th>Units sold</th><th>Revenue</th><th>Stock</th><th>Performance</th></tr></thead><tbody>{productPerformance.map((product) => <tr key={product.id}><td><div className={styles.productCell}><div className={styles.productImage}>{product.image ? <OptimizedImage src={product.image} alt={product.imageAlt} /> : <Package size={17} />}</div><strong>{product.name}</strong></div></td><td>{product.category}</td><td>{number(product.quantity)}</td><td>{money(product.revenue)}</td><td>{stockLabel(product)} <small className={styles.stockNumber}>({number(product.stock)})</small></td><td><span className={styles.performance}>{product.performance}</span></td></tr>)}</tbody></table></div> : <EmptyState>No products match these filters.</EmptyState>}</section>

    <div className={styles.threeColumn}><section className={styles.panel}><SectionHeading eyebrow="Customers" title="Customer analytics" />{summary.customers ? <><div className={styles.customerStats}><div><strong>{number(summary.newCustomers)}</strong><span>New customers</span></div><div><strong>{number(summary.returningCustomers)}</strong><span>Returning customers</span></div></div><div className={styles.miniChart}>{daily.map((item) => <span key={item.label} style={{ height: `${Math.max(item.customers * 12, item.customers ? 12 : 3)}px` }} title={`${item.label}: ${item.customers} new`} />)}</div><small className={styles.muted}>New customers are identified by their first paid order.</small></> : <EmptyState>No customers yet.</EmptyState>}</section><section className={styles.panel}><SectionHeading eyebrow="Geography" title="Geographic sales" />{geographicSales.length ? <div className={styles.simpleList}>{geographicSales.map((item) => <div className={styles.simpleRow} key={item.division}><span><MapPinned size={15} />{item.division}</span><strong>{money(item.revenue)}<small>{item.orders} orders</small></strong></div>)}</div> : <EmptyState>No geographic data yet.</EmptyState>}</section><section className={styles.panel}><SectionHeading eyebrow="Combos" title="Combo product analytics" />{comboProducts.length ? <><div className={styles.comboStats}><div><strong>{number(summary.comboOrders)}</strong><span>Units sold</span></div><div><strong>{money(summary.comboRevenue)}</strong><span>Combo revenue</span></div></div><div className={styles.simpleList}>{comboProducts.slice(0, 4).map((product) => <div className={styles.simpleRow} key={product.id}><span><Package size={15} />{product.name}</span><strong>{number(product.quantity)}<small>units</small></strong></div>)}</div></> : <EmptyState>No combo sales yet.</EmptyState>}</section></div>

    <section className={styles.insightsPanel}><div className={styles.insightTitle}><span className={styles.sparkIcon}><Sparkles size={18} /></span><div><span className={styles.eyebrow}>Decision support</span><h2>Insights</h2></div></div><div className={styles.insightGrid}>{insights.map((insight) => <article key={insight.title}><strong>{insight.title}</strong><p>{insight.text}</p></article>)}</div></section><div className={styles.footerNote}><RefreshCw size={14} />All figures are calculated from existing database records. Profit is shown only when cost price coverage is complete.</div>
  </main>;
}