'use client';
import { useState } from 'react';
const blank = { title: '', subtitle: '', image: '', link: '/shop', active: true, sortOrder: 0 };
export default function BannerManager({ initialBanners }) {
  const [banners, setBanners] = useState(initialBanners); const [form, setForm] = useState(null); const [message, setMessage] = useState(''); const [uploading, setUploading] = useState(false);
  async function upload(file) { setUploading(true); try { const body = new FormData(); body.append('file', file); const response = await fetch('/api/admin/upload', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setForm(current => ({ ...current, image: data.url })); } catch (error) { setMessage(error.message); } finally { setUploading(false); } }
  async function save(event) { event.preventDefault(); setMessage(''); const method = form.id ? 'PATCH' : 'POST'; const response = await fetch('/api/admin/banners', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form.id ? form : form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Banner save failed.'); setBanners(current => form.id ? current.map(item => item.id === data.id ? data : item) : [...current, data].sort((a, b) => a.sortOrder - b.sortOrder)); setForm(null); }
  async function archive(id) { if (!confirm('Archive this banner?')) return; const response = await fetch(`/api/admin/banners?id=${id}`, { method: 'DELETE' }); if (response.ok) setBanners(current => current.filter(item => item.id !== id)); }
  return <><div className="section-head"><div><div className="eyebrow" style={{ color: 'var(--coral)' }}>Homepage</div><h1>Banners</h1></div><button className="btn" onClick={() => setForm(blank)}>+ Add banner</button></div>{message && <p style={{ color: 'var(--coral)' }}>{message}</p>}{form && <form className="form banner-form" onSubmit={save}><h2>{form.id ? 'Edit banner' : 'Add banner'}</h2><label>Title<input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label>Subtitle<input value={form.subtitle || ''} onChange={event => setForm({ ...form, subtitle: event.target.value })} /></label><label>Link<input value={form.link || ''} onChange={event => setForm({ ...form, link: event.target.value })} /></label><label>Display order<input type="number" value={form.sortOrder} onChange={event => setForm({ ...form, sortOrder: event.target.value })} /></label><label>Hero image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={event => upload(event.target.files?.[0])} /></label>{form.image && <img className="banner-preview" src={form.image} alt="Banner preview" />}<label className="check-label"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })} /> Active on homepage</label><button className="btn" disabled={uploading}>{uploading ? 'Uploading...' : 'Save banner'}</button> <button type="button" onClick={() => setForm(null)}>Cancel</button></form>}<div className="banner-list">{banners.map(banner => <article className="banner-row" key={banner.id}>{banner.image ? <img src={banner.image} alt="" /> : <div className="banner-placeholder">No image</div>}<div><strong>{banner.title}</strong><p className="muted">Order {banner.sortOrder} · {banner.active ? 'Active' : 'Archived'}</p></div><button onClick={() => setForm({ ...banner })}>Edit</button><button onClick={() => archive(banner.id)}>Archive</button></article>)}</div></>;
}
