'use client';

import { useState } from 'react';
import MediaUploader from '@/components/admin/MediaUploader';

const empty = { name:'', slug:'', description:'', image:'', active:true };
export default function CategoryManager({ initialCategories }) {
  const [categories, setCategories] = useState(initialCategories); const [form, setForm] = useState(null); const [message, setMessage] = useState('');
  async function save(event) { event.preventDefault(); const response = await fetch('/api/admin/categories', { method:form.id ? 'PATCH' : 'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Unable to save category.'); setCategories(items => form.id ? items.map(item => item.id === data.id ? {...data, _count:item._count} : item) : [...items, {...data,_count:{products:0}}]); setForm(null); }
  async function archive(id) { if (!confirm('Archive this empty category?')) return; const response = await fetch(`/api/admin/categories?id=${id}`, {method:'DELETE'}); if (response.ok) setCategories(items => items.filter(item => item.id !== id)); else setMessage((await response.json()).error); }
  return <><div className="section-head"><div><div className="eyebrow">Catalogue</div><h1>Categories</h1></div><button className="btn" onClick={() => setForm(empty)}>+ Add category</button></div>{message && <p className="admin-message">{message}</p>}
    {form && <form className="admin-form category-form" onSubmit={save}><div className="admin-form-head"><h2>{form.id ? 'Edit category' : 'Add category'}</h2><button type="button" onClick={() => setForm(null)}>Cancel</button></div><div className="admin-form-grid"><section><label>Category name<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e => setForm({...form,slug:e.target.value})}/></label><label>Description<textarea value={form.description || ''} onChange={e => setForm({...form,description:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={form.active} onChange={e => setForm({...form,active:e.target.checked})}/> Active</label></section><MediaUploader label="Category image" multiple={false} images={form.image ? [{url:form.image,isPrimary:true}] : []} onChange={images => setForm({...form,image:images[0]?.url || ''})}/></div><div className="admin-form-actions"><button className="btn">Save category</button></div></form>}
    <div className="admin-table-wrap"><table className="table"><thead><tr><th>Image</th><th>Category</th><th>Slug</th><th>Products</th><th>Status</th><th>Actions</th></tr></thead><tbody>{categories.map(category => <tr key={category.id}><td>{category.image ? <img className="admin-thumbnail" src={category.image} alt={category.name}/> : <div className="no-image">No image</div>}</td><td><strong>{category.name}</strong></td><td>{category.slug}</td><td>{category._count.products}</td><td><span className={category.active ? 'status active' : 'status'}>{category.active ? 'Active' : 'Archived'}</span></td><td><button onClick={() => setForm({...category})}>Edit</button> <button onClick={() => archive(category.id)}>Archive</button></td></tr>)}</tbody></table></div></>;
}
