'use client';

import { useState } from 'react';
import MediaUploader from '@/components/admin/MediaUploader';

const empty = { name:'', slug:'', description:'', image:'', active:true, attributeIds:[] };
export default function CategoryManager({ initialCategories, attributes = [] }) {
  const [categories, setCategories] = useState(initialCategories); const [form, setForm] = useState(null); const [message, setMessage] = useState(''); const [actionId, setActionId] = useState(null);
  async function save(event) { event.preventDefault(); const response = await fetch('/api/admin/categories', { method:form.id ? 'PATCH' : 'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Unable to save category.'); setCategories(items => form.id ? items.map(item => item.id === data.id ? {...data, _count:item._count} : item) : [...items, {...data,_count:{products:0}}]); setForm(null); }
  async function archive(id) { if (!confirm('Archive this empty category?')) return; const response = await fetch(`/api/admin/categories?id=${id}`, {method:'DELETE'}); if (response.ok) setCategories(items => items.filter(item => item.id !== id)); else setMessage((await response.json()).error); }
  return <><div className="admin-page-heading"><div><div className="eyebrow">Catalogue</div><h1>Categories</h1><p className="muted">Manage and organize your store catalogue.</p></div><button className="btn" onClick={() => setForm(empty)}>+ Add category</button></div>{message && <p className="admin-message">{message}</p>}
    {form && <form className="admin-form category-form" onSubmit={save}><div className="admin-form-head"><h2>{form.id ? 'Edit category' : 'Add category'}</h2><button type="button" onClick={() => setForm(null)}>Cancel</button></div><div className="admin-form-grid"><section><label>Category name<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e => setForm({...form,slug:e.target.value})}/></label><label>Description<textarea value={form.description || ''} onChange={e => setForm({...form,description:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={form.active} onChange={e => setForm({...form,active:e.target.checked})}/> Active</label><fieldset><legend>Enabled attributes</legend>{attributes.map(attribute => <label className="check-label" key={attribute.id}><input type="checkbox" checked={(form.attributeIds || form.attributes?.map(item => item.attributeId) || []).includes(attribute.id)} onChange={e => setForm({...form,attributeIds:e.target.checked ? [...new Set([...(form.attributeIds || []),attribute.id])] : (form.attributeIds || []).filter(id => id !== attribute.id)})}/>{attribute.name}</label>)}</fieldset></section><MediaUploader label="Category image" multiple={false} images={form.image ? [{url:form.image,isPrimary:true}] : []} onChange={images => setForm({...form,image:images[0]?.url || ''})}/></div><div className="admin-form-actions"><button className="btn">Save category</button></div></form>}
    <div className="admin-table-wrap"><table className="table"><thead><tr><th>Image</th><th>Category</th><th>Slug</th><th>Products</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{categories.map(category => <tr key={category.id}><td>{category.image ? <img className="admin-thumbnail" src={category.image} alt={category.name} onError={event => { event.currentTarget.style.display = 'none'; }} /> : <div className="no-image">No image</div>}</td><td><strong title={category.name}>{category.name}</strong></td><td>{category.slug}</td><td><span className="stock">{category._count.products}</span></td><td><span className={category.active ? 'status active' : 'status'}>{category.active ? 'Active' : 'Archived'}</span></td><td><span className="admin-date">{category.createdAt ? new Date(category.createdAt).toLocaleDateString('en-GB') : '—'}</span></td><td><div className="admin-action-menu"><button type="button" aria-label={`Actions for ${category.name}`} onClick={() => setActionId(actionId === category.id ? null : category.id)}>⋮</button>{actionId === category.id && <div className="admin-action-popover"><button type="button" onClick={() => { setActionId(null); setForm({...category}); }}>Edit</button><button type="button" onClick={() => { setActionId(null); archive(category.id); }}>Archive</button></div>}</div></td></tr>)}</tbody></table></div></>;
}
