'use client';

import { useState } from 'react';

const blank = id => ({ entityId: id, metaTitle: '', metaDescription: '', focusKeyword: '', canonicalUrl: '', robotsIndex: 'INDEX', robotsFollow: 'FOLLOW', ogTitle: '', ogDescription: '', ogImage: '' });

export default function EntitySEOManager({ title, eyebrow, endpoint, entities, idKey = 'id', nameKey = 'name' }) {
  const [items, setItems] = useState(entities);
  const [selectedId, setSelectedId] = useState(entities[0]?.[idKey] || '');
  const [form, setForm] = useState(() => entities[0] ? { ...blank(entities[0][idKey]), ...(entities[0].seo || {}) } : blank(''));
  const [message, setMessage] = useState('');
  function select(event) { const id = event.target.value; const entity = items.find(item => item[idKey] === id); setSelectedId(id); setForm({ ...blank(id), ...(entity?.seo || {}) }); setMessage(''); }
  async function save(event) { event.preventDefault(); const response = await fetch(endpoint, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Unable to save SEO settings.'); setItems(current => current.map(item => item[idKey] === selectedId ? { ...item, seo: data } : item)); setForm(current => ({ ...current, ...data })); setMessage('SEO settings saved.'); }
  return <><div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="muted">Manage metadata without changing existing URLs or content.</p></div></div>{!items.length ? <p className="muted">No records found.</p> : <form className="admin-form" onSubmit={save}><label>Choose record<select value={selectedId} onChange={select}>{items.map(item => <option key={item[idKey]} value={item[idKey]}>{item[nameKey]}</option>)}</select></label><div className="admin-form-grid"><section><h3>Search result</h3><label>Meta title<input maxLength="191" value={form.metaTitle || ''} onChange={event => setForm({ ...form, metaTitle: event.target.value })} /></label><label>Meta description<textarea maxLength="191" value={form.metaDescription || ''} onChange={event => setForm({ ...form, metaDescription: event.target.value })} /></label><label>Focus keyword<input value={form.focusKeyword || ''} onChange={event => setForm({ ...form, focusKeyword: event.target.value })} /></label><label>Canonical URL<input value={form.canonicalUrl || ''} onChange={event => setForm({ ...form, canonicalUrl: event.target.value })} /></label></section><section><h3>Social and robots</h3><label>Open Graph title<input value={form.ogTitle || ''} onChange={event => setForm({ ...form, ogTitle: event.target.value })} /></label><label>Open Graph description<textarea value={form.ogDescription || ''} onChange={event => setForm({ ...form, ogDescription: event.target.value })} /></label><label>Open Graph image<input value={form.ogImage || ''} onChange={event => setForm({ ...form, ogImage: event.target.value })} /></label><label>Indexing<select value={form.robotsIndex} onChange={event => setForm({ ...form, robotsIndex: event.target.value })}><option value="INDEX">Index</option><option value="NOINDEX">No index</option></select></label><label>Link following<select value={form.robotsFollow} onChange={event => setForm({ ...form, robotsFollow: event.target.value })}><option value="FOLLOW">Follow</option><option value="NOFOLLOW">No follow</option></select></label></section></div><button className="btn">Save SEO settings</button>{message && <p className="admin-message">{message}</p>}</form>}</>;
}
