'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import MediaUploader from '@/components/admin/MediaUploader';

const makeEmpty = categories => ({ name:'', slug:'', sku:'', categoryId:categories[0]?.id || '', regularPrice:'', salePrice:'', stock:0, lowStock:5, brand:'', shortDescription:'', description:'', active:true, featured:false, images:[] });

export default function ProductManager({ initialProducts, categories }) {
  const [products, setProducts] = useState(initialProducts);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState(makeEmpty(categories));
  const [query, setQuery] = useState('');
  const [message, setMessage] = useState('');
  const visible = useMemo(() => products.filter(product => `${product.name} ${product.sku} ${product.category?.name || ''} ${product.brand || ''}`.toLowerCase().includes(query.toLowerCase())), [products, query]);
  function open(product) { setEditing(product?.id || 'new'); setForm(product ? { ...product, regularPrice: String(product.regularPrice), salePrice: product.salePrice == null ? '' : String(product.salePrice), images: product.images || [] } : makeEmpty(categories)); setMessage(''); }
  async function save(event) { event.preventDefault(); const response = await fetch('/api/admin/products', { method: editing === 'new' ? 'POST' : 'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(editing === 'new' ? form : { id: editing, ...form }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Unable to save product.'); setProducts(current => editing === 'new' ? [data, ...current] : current.map(product => product.id === data.id ? data : product)); setEditing(null); setMessage('Product saved.'); }
  async function archive(id) { if (!confirm('Archive this product? It will disappear from the storefront but historical orders remain.')) return; const response = await fetch(`/api/admin/products?id=${id}`, { method:'DELETE' }); if (response.ok) setProducts(current => current.filter(product => product.id !== id)); }
  return <><div className="section-head"><div><div className="eyebrow">Catalogue</div><h1>Products</h1></div><button className="btn" onClick={() => open()}>+ Add product</button></div>
    {message && <p className="admin-message">{message}</p>}
    {editing && <form className="admin-form" onSubmit={save}><div className="admin-form-head"><h2>{editing === 'new' ? 'Add product' : 'Edit product'}</h2><button type="button" onClick={() => setEditing(null)}>Cancel</button></div><div className="admin-form-grid"><section><h3>Basic information</h3><label>Product name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e => setForm({...form, slug:e.target.value})}/></label><label>SKU<input required value={form.sku} onChange={e => setForm({...form, sku:e.target.value})}/></label><label>Short description<textarea value={form.shortDescription || ''} onChange={e => setForm({...form, shortDescription:e.target.value})}/></label><label>Full description<textarea rows="6" value={form.description || ''} onChange={e => setForm({...form, description:e.target.value})}/></label></section><section><h3>Pricing & inventory</h3><label>Regular price<input type="number" min="0" required value={form.regularPrice} onChange={e => setForm({...form, regularPrice:e.target.value})}/></label><label>Sale price<input type="number" min="0" value={form.salePrice || ''} onChange={e => setForm({...form, salePrice:e.target.value})}/></label><label>Stock quantity<input type="number" min="0" required value={form.stock} onChange={e => setForm({...form, stock:Number(e.target.value)})}/></label><label>Low-stock threshold<input type="number" min="0" required value={form.lowStock} onChange={e => setForm({...form, lowStock:Number(e.target.value)})}/></label><h3>Organisation</h3><label>Category<select required value={form.categoryId} onChange={e => setForm({...form, categoryId:e.target.value})}>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Brand<input value={form.brand || ''} onChange={e => setForm({...form, brand:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={form.featured} onChange={e => setForm({...form, featured:e.target.checked})}/> Featured on homepage</label><label className="check-label"><input type="checkbox" checked={form.active} onChange={e => setForm({...form, active:e.target.checked})}/> Active</label></section></div><MediaUploader label="Product images" images={form.images || []} onChange={images => setForm({...form, images})}/><div className="admin-form-actions"><button className="btn">Save product</button><button type="button" onClick={() => setEditing(null)}>Cancel</button></div></form>}
    <div className="admin-toolbar"><input placeholder="Search name, SKU, category or brand" value={query} onChange={e => setQuery(e.target.value)}/><span>{visible.length} products</span></div><div className="admin-table-wrap"><table className="table product-admin-table"><thead><tr><th>Image</th><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(product => <tr key={product.id}><td>{product.images?.[0]?.url ? <img className="admin-thumbnail" src={product.images[0].url} alt={product.name}/> : <div className="no-image">No image</div>}</td><td><strong>{product.name}</strong>{product.featured && <small className="featured-mark">Featured</small>}</td><td>{product.sku}</td><td>{product.category?.name}</td><td>৳{Number(product.salePrice || product.regularPrice).toLocaleString()}{product.salePrice && <small className="old-price">৳{Number(product.regularPrice).toLocaleString()}</small>}</td><td className={product.stock <= product.lowStock ? 'low-stock' : ''}>{product.stock}</td><td><span className={product.active ? 'status active' : 'status'}>{product.active ? 'Active' : 'Archived'}</span></td><td><button onClick={() => open(product)}>Edit</button> <button onClick={() => archive(product.id)}>Archive</button></td></tr>)}</tbody></table></div></>;
}
